import ezdxf
from math import tan, radians
import time
timestr = '20260227-111656-0'
D = 4.0
L = 12.0
S = 7.0
K = 2.6
runout = 1.5
chamfer_head = 1.2
doc = ezdxf.new('R2010', setup=True, units=4)
msp = doc.modelspace()
doc.layers.add(name='Main', color=7, linetype='CONTINUOUS', lineweight=50)
doc.layers.add(name='Thread', color=4, linetype='CONTINUOUS', lineweight=25)
doc.layers.add(name='Hatches', color=8, linetype='CONTINUOUS', lineweight=25)
doc.layers.add(name='Axises', color=6, linetype='CENTER')
doc.layers.add(name='Measure', color=170, lineweight=25)
msp.add_line((-5, 0), (K + L + 5, 0), dxfattribs={'layer': 'Axises'})
p0 = (0, 0)
p1 = (0, 3.5)
fh = 1.2
p2 = (1.4000000000000001, 3.5)
p3 = (2.6, 2.8071796769724493)
p4 = (2.6, 2.0)
thr_len = 10.5
p5 = (13.1, 2.0)
p6 = (14.6, 0.5)
p7 = (14.6, 0)
line1 = msp.add_line(p0, p1, dxfattribs={'layer': 'Main'})
line2 = msp.add_line(p1, p2, dxfattribs={'layer': 'Main'})
line3 = msp.add_line(p2, p3, dxfattribs={'layer': 'Main'})
line4 = msp.add_line(p3, p4, dxfattribs={'layer': 'Main'})
line5 = msp.add_line(p4, p5, dxfattribs={'layer': 'Main'})
line6 = msp.add_line(p5, p6, dxfattribs={'layer': 'Main'})
line7 = msp.add_line(p6, p7, dxfattribs={'layer': 'Main'})
d1 = 2.5
offset = 0.75
thr_line_start = (2.6, 1.25)
thr_line_end = (13.1, 1.25)
line_thr1 = msp.add_line(thr_line_start, thr_line_end, dxfattribs={'layer': 'Thread'})
thr_runout_start = (13.1, 1.25)
thr_runout_end = (14.6, -1.75)
line_thr2 = msp.add_line(thr_runout_start, thr_runout_end, dxfattribs={'layer': 'Thread'})
line_thr3 = msp.add_line((p4[0], p4[1]), (p4[0], p4[1] - offset), dxfattribs={'layer': 'Thread'})
line_thr_boundary = msp.add_line((p5[0], p5[1]), (p5[0], p5[1] - offset - 0.5), dxfattribs={'layer': 'Thread'})
# Отражение основных линий
line1_sym = line1.copy()
msp.add_entity(line1_sym)
line1_sym.scale(1, -1, 1)
line2_sym = line2.copy()
msp.add_entity(line2_sym)
line2_sym.scale(1, -1, 1)
line3_sym = line3.copy()
msp.add_entity(line3_sym)
line3_sym.scale(1, -1, 1)
line4_sym = line4.copy()
msp.add_entity(line4_sym)
line4_sym.scale(1, -1, 1)
line5_sym = line5.copy()
msp.add_entity(line5_sym)
line5_sym.scale(1, -1, 1)
line6_sym = line6.copy()
msp.add_entity(line6_sym)
line6_sym.scale(1, -1, 1)
line7_sym = line7.copy()
msp.add_entity(line7_sym)
line7_sym.scale(1, -1, 1)
# Отражение линий резьбы
line_thr1_sym = line_thr1.copy()
msp.add_entity(line_thr1_sym)
line_thr1_sym.scale(1, -1, 1)
line_thr2_sym = line_thr2.copy()
msp.add_entity(line_thr2_sym)
line_thr2_sym.scale(1, -1, 1)
line_thr3_sym = line_thr3.copy()
msp.add_entity(line_thr3_sym)
line_thr3_sym.scale(1, -1, 1)
line_thr_boundary_sym = line_thr_boundary.copy()
msp.add_entity(line_thr_boundary_sym)
line_thr_boundary_sym.scale(1, -1, 1)
dim_attrs = {'dimtxt': 2.5, 'dimtad': 0, 'dimtvp': 0, 'dimdle': 0, 'dimblk': 'EZ_ARROW_FILLED'}
dim_total = msp.add_linear_dim(base=(K+L+10, -5), p1=(0,0), p2=(K+L,0), dimstyle='STANDARD', override=dim_attrs, dxfattribs={'layer': 'Measure'})
dim_total.render()
dim_thr_len = msp.add_linear_dim(base=(K+L+15, D/2+5), p1=(K, D/2), p2=(K+thr_len, D/2), dimstyle='STANDARD', override=dim_attrs, dxfattribs={'layer': 'Measure'})
dim_thr_len.render()
dim_s = msp.add_linear_dim(base=(-10, S/2), p1=(0, S/2), p2=(0, -S/2), text='S7.0', dimstyle='STANDARD', angle=90, override=dim_attrs, dxfattribs={'layer': 'Measure'})
dim_s.render()
dim_k = msp.add_linear_dim(base=(-5, S/2+7.5), p1=(0,0), p2=(K,0), dimstyle='STANDARD', override=dim_attrs, dxfattribs={'layer': 'Measure'})
dim_k.render()
dim_d = msp.add_linear_dim(base=(K+L+22.5, D/2), p1=(K+thr_len, D/2), p2=(K+thr_len, -D/2), text='M4.0', dimstyle='STANDARD', angle=90, override=dim_attrs, dxfattribs={'layer': 'Measure'})
dim_d.render()
vert_line_up = (1.4000000000000001, 8.5)
ang_dim_head = msp.add_angular_dim_2l(base=(K-5, S/2+10), line1=(p2, p3), line2=(p2, vert_line_up), dimstyle='EZ_CURVED', override=dim_attrs, dxfattribs={'layer': 'Measure'})
ang_dim_head.render()
chamfer_dim = msp.add_linear_dim(base=(23.1, 10.0), p1=p5, p2=p6, dimstyle='STANDARD', override=dim_attrs, text='1.5x45°', dxfattribs={'layer': 'Measure'})
chamfer_dim.render()
doc.saveas('./20260227-111656-01.dxf')
